MiPrimeraAplicacionWebConEntityFramework/Models/Marca.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiPrimeraAplicacionWebConEntityFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marca
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Marca()
        {
            this.Bus = new HashSet<Bus>();
        }
    
        public int IIDMARCA { get; set; }
        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<int> BHABILITADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bus> Bus { get; set; }
    }
}

MiPrimeraAplicacionWebConEntityFramework/Controllers/MarcaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MiPrimeraAplicacionWebConEntityFramework.Models;
namespace MiPrimeraAplicacionWebConEntityFramework.Controllers
{
    public class MarcaController : Controller
    {
        // GET: Marca
        public ActionResult Index(MarcaCLS omarcaCLS)
        {
            string nombreMarca = omarcaCLS.nombre;
            List<MarcaCLS> listaMarca = null;
            using (var bd = new BDPasajeEntities())
            {
                if(omarcaCLS.nombre == null) { 
                listaMarca = (from marca in bd.Marca
                              where marca.BHABILITADO == 1
                                             select new MarcaCLS
                                             {
                                                 iidmarca = marca.IIDMARCA,
                                                 nombre = marca.NOMBRE,
                                                 descripcion = marca.DESCRIPCION
                                             }).ToList();
                }
                else
                {
                    listaMarca = (from marca in bd.Marca
                                  where marca.BHABILITADO == 1
                                  && marca.NOMBRE.Contains(nombreMarca)
                                  select new MarcaCLS
                                  {
                                      iidmarca = marca.IIDMARCA,
                                      nombre = marca.NOMBRE,
                                      descripcion = marca.DESCRIPCION
                                  }).ToList();
                }
            }
            return View(listaMarca);
        }
        //Muestra la lista
        public ActionResult Agregar()
        {
            return View();    
        }

        public ActionResult Editar(int uf)
        {
            MarcaCLS oMarcaCLS = new MarcaCLS();
            using(var bd=new BDPasajeEntities())
            {
                Marca oMarca = bd.Marca.Where(p => p.IIDMARCA.Equals(uf)).First();
                oMarcaCLS.iidmarca = oMarca.IIDMARCA;
                oMarcaCLS.nombre = oMarca.NOMBRE;
                oMarcaCLS.descripcion = oMarca.DESCRIPCION;
            }
            return View(oMarcaCLS);
        }

        [HttpPost]
        public ActionResult Editar(MarcaCLS oMarcaCLS)
        {
            int nregistrosEncontrados = 0;
            string nombreMarca = oMarcaCLS.nombre;
            int iidmarca = oMarcaCLS.iidmarca;
            using (var bd = new BDPasajeEntities())
            {
                nregistrosEncontrados = bd.Marca.Where(p => p.NOMBRE.Equals(nombreMarca) && !p.IIDMARCA.Equals(iidmarca)).Count();
            }

            if (!ModelState.IsValid || nregistrosEncontrados >= 1)
            {
                if (nregistrosEncontrados >= 1) oMarcaCLS.mensajeError = "Ya se encuentra registrada la marca";
                return View(oMarcaCLS);
            }
            

            int idMarca = oMarcaCLS.iidmarca;
            using(var bd=new BDPasajeEntities())
            {                
                Marca oMarca = bd.Marca.Where(p => p.IIDMARCA.Equals(idMarca)).First();
                oMarca.NOMBRE = oMarcaCLS.nombre;
                oMarca.DESCRIPCION = oMarcaCLS.descripcion;
                bd.SaveChanges();
            }

            return RedirectToAction("Index");
        }
            
        //Hace la inserción
        [HttpPost]
        public ActionResult Agregar(MarcaCLS oMarcaCLS)
        {
            int nregistrosEncontrados = 0;
            string nombreMarca = oMarcaCLS.nombre;
            using (var bd = new BDPasajeEntities())
            {
                nregistrosEncontrados = bd.Marca.Where(p => p.NOMBRE.Equals(nombreMarca)).Count();
            }
            /////////////////////////////////
            if (!ModelState.IsValid || nregistrosEncontrados  >= 1)
            {
                if (nregistrosEncontrados >= 1) oMarcaCLS.mensajeError = "El nombre Marca ya existe";
                return View(oMarcaCLS);
            }
            else
            {
                using (var bd = new BDPasajeEntities())
                {
                    Marca oMarca = new Marca();
                    oMarca.NOMBRE = oMarcaCLS.nombre;
                    oMarca.DESCRIPCION = oMarcaCLS.descripcion;
                    oMarca.BHABILITADO = 1;
                    bd.Marca.Add(oMarca);
                    bd.SaveChanges();
                }
            }

            return RedirectToAction("Index");
        }

        public ActionResult Eliminar(int uf)
        {
            using(var bd=new BDPasajeEntities())
            {
                Marca oMarca = bd.Marca.Where(p => p.IIDMARCA.Equals(uf)).First();
                oMarca.BHABILITADO = 0;
                bd.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

MiPrimeraAplicacionWebConEntityFramework/Views/Marca/Agregar.cshtml
@using MiPrimeraAplicacionWebConEntityFramework.Models
@model MarcaCLS
@{
    ViewBag.Title = "Agregar";
}

<h2>Agregar</h2>
<div class="row">
    <div class="col-md-6">
        @using (Html.BeginForm("Agregar", "Marca", FormMethod.Post, new { @id = "frmAgregar" }))
        {
            <div>
                @Html.LabelFor(p => p.nombre)
                @Html.TextBoxFor(p => p.nombre, new { @class = "form-control" })
                @Html.ValidationMessage("nombre", new { @class="text-danger"})
                    @if (Model!=null &&  Model.mensajeError != null)
                    {
                        @Html.Label(Model.mensajeError, new {@class="text-danger"})
                    }
            </div>

            <div>
                @Html.LabelFor(p => p.descripcion)
                @Html.TextBoxFor(p => p.descripcion, new { @class = "form-control" })
                @Html.ValidationMessage("descripcion", new { @class = "text-danger" })
            </div>
            <br />
            <div style="margin:auto">
                <input type="submit" class="btn btn-primary" value="Guardar" />
                @Html.ActionLink("Regresar", "Index", "Marca", null, new { @class = "btn btn-danger" })
            </div>
        }
    </div>
</div>

<script>
    var frmAgregando = document.getElementById("frmAgregar");
    frmAgregando.onsubmit = function (e) {
        e.preventDefault();
        if (confirm("¿Deseas guardar los combios?") == 1) {
            frmAgregando.submit();
        }
    }
</script>

MiPrimeraAplicacionWebConEntityFramework/Views/Marca/Editar.cshtml
@using MiPrimeraAplicacionWebConEntityFramework.Models
@model MarcaCLS
@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>

<div class="row">
    <div class="col-md-6">
        @using (Html.BeginForm("Editar", "Marca", FormMethod.Post, new { @id="frmEditar"}))
        {
        <div>
            @Html.LabelFor(p => p.iidmarca)
            @Html.TextBoxFor(p => p.iidmarca, new { @class = "form-control", @readOnly = true })
            @Html.ValidationMessage("iidmarca", new { @class = "text-danger" })
        </div>

        <div>
            @Html.LabelFor(p => p.nombre)
            @Html.TextBoxFor(p => p.nombre, new { @class = "form-control" })
            @Html.ValidationMessage("nombre", new { @class = "text-danger" })
            @if (Model != null && Model.mensajeError != null)
            {
                @Html.Label(Model.mensajeError, new { @class = "text-danger" })
            }
        </div>

            <div>
                @Html.LabelFor(p => p.descripcion)
                @Html.TextBoxFor(p => p.descripcion, new { @class = "form-control" })
                @Html.ValidationMessage("descripcion", new { @class = "text-danger" })
            </div>
            <br />
            <div style="margin:auto">
                <input type="submit" class="btn btn-primary" value="Guardar" />
                @Html.ActionLink("Regresar", "Index", "Marca", null, new {@class="btn btn-danger"})
            </div>
        }
    </div>
</div>

<script>
    var frmEditar = document.getElementById("frmEditar");
    frmEditar.onsubmit = function (e) {
        e.preventDefault();
        if (confirm("¿Deseas guardar los combios?") == 1) {
            frmEditar.submit();
        }
    }
</script>

MiPrimeraAplicacionWebConEntityFramework/Views/Marca/Index.cshtml
@using MiPrimeraAplicacionWebConEntityFramework.Models
@model List<MarcaCLS>
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
@Html.ActionLink("Agregar", "Agregar", "Marca", null, new { @class = "btn btn-primary" })

@using(Html.BeginForm("Index", "Marca", FormMethod.Post)) { 

@Html.Label("Ingrese nombre Marca")
@Html.TextBox("nombre")
<input type="submit" class="btn btn-success" value="Buscar" />
<table class="table table-bordered table-hover">

    <thead>
        <tr>
            <td width="10%">@Html.LabelFor(p=>Model[0].iidmarca)</td>
            <td width="20%">@Html.LabelFor(p=>Model[0].nombre)</td>
            <td width="50%">@Html.LabelFor(p=>Model[0].descripcion)</td>
            <td width="15%">Operaciones</td>
        </tr>

    </thead>
    <tbody>
        @foreach(var item in Model) {
        <tr>
            <td>@item.iidmarca</td>
            <td>@item.nombre</td>
            <td>@item.descripcion</td>
            <td>
                @Html.ActionLink("Editar", "Editar", "Marca", new { uf = @item.iidmarca }, new { @class = "btn btn-primary" })
                @Html.ActionLink("Eliminar", "Eliminar", "Marca", new { uf = @item.iidmarca }, new { @class = "btn btn-danger", @onclick = "eliminar()" })
            </td>
        </tr>
        }
    </tbody>
</table>
}

<script>
    function eliminar() {
        if (confirm("¿Desea eliminar el registro realmente?") == 1) {
            //Pone Si
            alert("Se elimino correctamente");
        } else {
            //Pone No
            event.preventDefault();
        }
    }
</script>