MiPrimeraAplicacionWebConEntityFramework/Models/Sucursal.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiPrimeraAplicacionWebConEntityFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sucursal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sucursal()
        {
            this.Bus = new HashSet<Bus>();
        }
    
        public int IIDSUCURSAL { get; set; }
        public string NOMBRE { get; set; }
        public string DIRECCION { get; set; }
        public string TELEFONO { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> FECHAAPERTURA { get; set; }
        public Nullable<int> BHABILITADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bus> Bus { get; set; }
    }
}

MiPrimeraAplicacionWebConEntityFramework/Controllers/SucursalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MiPrimeraAplicacionWebConEntityFramework.Models;
namespace MiPrimeraAplicacionWebConEntityFramework.Controllers
{
    public class SucursalController : Controller
    {
        // GET: Sucursal
        public ActionResult Index(SucursalCLS oSucursalCLS)
        {
            string nombreSucursal = oSucursalCLS.nombre;
            List<SucursalCLS> listaSucursal = null; 
            using(var bd= new BDPasajeEntities())
            {
                if (oSucursalCLS.nombre == null)
                {
                    listaSucursal = (from sucursal in bd.Sucursal
                                 where sucursal.BHABILITADO == 1
                                 select new SucursalCLS
                                 {
                                     iidsucursal = sucursal.IIDSUCURSAL,
                                     nombre = sucursal.NOMBRE,
                                     telefono = sucursal.TELEFONO,
                                     email = sucursal.EMAIL
                                 }).ToList();
                }
                else
                {
                    listaSucursal = (from sucursal in bd.Sucursal
                                     where sucursal.BHABILITADO == 1
                                     && sucursal.NOMBRE.Contains(nombreSucursal)
                                     select new SucursalCLS
                                     {
                                         iidsucursal = sucursal.IIDSUCURSAL,
                                         nombre = sucursal.NOMBRE,
                                         telefono = sucursal.TELEFONO,
                                         email = sucursal.EMAIL
                                     }).ToList();
                }
            }
            return View(listaSucursal);
        }

        public ActionResult Editar(int id)
        {
            SucursalCLS oSucursalCLS = new SucursalCLS();
            using (var bd= new BDPasajeEntities())
            {
                Sucursal oSucursal = bd.Sucursal.Where(p => p.IIDSUCURSAL.Equals(id)).First();
                oSucursalCLS.iidsucursal = oSucursal.IIDSUCURSAL;
                oSucursalCLS.nombre = oSucursal.NOMBRE;
                oSucursalCLS.direccion = oSucursal.DIRECCION;
                oSucursalCLS.telefono = oSucursal.TELEFONO;
                oSucursalCLS.email = oSucursal.EMAIL;
                oSucursalCLS.fechaApertura = (DateTime) oSucursal.FECHAAPERTURA;
            }
            return View(oSucursalCLS);
        }

        public ActionResult Agregar()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Agregar(SucursalCLS oSucursalCLS)
        {
            int nregistrosEncontrados = 0;
            string nombreSucursal = oSucursalCLS.nombre;
            using (var bd = new BDPasajeEntities())
            {
                nregistrosEncontrados = bd.Sucursal.Where(p => p.NOMBRE.Equals(nombreSucursal)).Count();
            }

            if (!ModelState.IsValid || nregistrosEncontrados >= 1)
            {
                if (nregistrosEncontrados >= 1) oSucursalCLS.mensajeError = "Ya existe la Sucursal a ingresar";
                return View(oSucursalCLS);
            }
            using(var bd = new BDPasajeEntities())
            {
                Sucursal oSucursal = new Sucursal();
                oSucursal.NOMBRE = oSucursalCLS.nombre;
                oSucursal.DIRECCION = oSucursalCLS.direccion;
                oSucursal.TELEFONO = oSucursalCLS.telefono;
                oSucursal.EMAIL = oSucursalCLS.email;
                oSucursal.FECHAAPERTURA = oSucursalCLS.fechaApertura;
                oSucursal.BHABILITADO = 1;
                bd.Sucursal.Add(oSucursal);
                bd.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Editar(SucursalCLS oSucursalCLS)
        {
            int nregistrosAfectados = 0;
            string nombreSucursal = oSucursalCLS.nombre;
            int idSucursal = oSucursalCLS.iidsucursal;
            using (var bd = new BDPasajeEntities())
            {
                nregistrosAfectados = bd.Sucursal.Where(p => p.NOMBRE.Equals(nombreSucursal) && !p.IIDSUCURSAL.Equals(idSucursal)).Count();
            }


            if (!ModelState.IsValid || nregistrosAfectados >= 1)
            {
                if (nregistrosAfectados >= 1) oSucursalCLS.mensajeError = "Ya existe la Sucursal";
                return View(oSucursalCLS);
            }

            using(var bd=new BDPasajeEntities())
            {
                Sucursal oSucursal = bd.Sucursal.Where(p => p.IIDSUCURSAL.Equals(idSucursal)).First();

                oSucursal.NOMBRE = oSucursalCLS.nombre;
                oSucursal.DIRECCION = oSucursalCLS.direccion;
                oSucursal.TELEFONO = oSucursalCLS.telefono;
                oSucursal.EMAIL = oSucursalCLS.email;
                oSucursal.FECHAAPERTURA = oSucursalCLS.fechaApertura;

                bd.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        public ActionResult Eliminar(int id)
        {
            using (var bd = new BDPasajeEntities())
            {
                Sucursal oSucursal = bd.Sucursal.Where(p => p.IIDSUCURSAL.Equals(id)).First();
                oSucursal.BHABILITADO = 0;
                bd.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

MiPrimeraAplicacionWebConEntityFramework/Views/Sucursal/Agregar.cshtml
@using MiPrimeraAplicacionWebConEntityFramework.Models
@model SucursalCLS
@{
    ViewBag.Title = "Agregar";
}

<h2>Agregar</h2>
<div class="row">
    <div class="col-md-6">
        @using (Html.BeginForm("Agregar", "Sucursal", FormMethod.Post, new { @id="frmSucursal"}))
        {
        <div>
            @Html.LabelFor(p => p.nombre)
            @Html.TextBoxFor(p => p.nombre, new { @class = "form-control" })
            @Html.ValidationMessage("nombre", new { @class = "text-danger" })
            @if (Model != null && Model.mensajeError != null)
            {
                @Html.Label(Model.mensajeError, new { @class = "text-danger" })
            }
        </div>

            <div>
                @Html.LabelFor(p => p.direccion)
                @Html.TextBoxFor(p => p.direccion, new { @class = "form-control" })
                @Html.ValidationMessage("direccion", new { @class = "text-danger" })
            </div>

            <div>
                @Html.LabelFor(p => p.telefono)
                @Html.TextBoxFor(p => p.telefono, new { @class = "form-control" })
                @Html.ValidationMessage("telefono", new { @class = "text-danger" })
            </div>

            <div>
                @Html.LabelFor(p => p.email)
                @Html.TextBoxFor(p => p.email, new { @class = "form-control" })
                @Html.ValidationMessage("email", new { @class = "text-danger" })
            </div>

            <div>
                @Html.LabelFor(p => p.fechaApertura)
                @Html.EditorFor(p => p.fechaApertura, new { htmlAttributes = new { @class = "form-control" } } )
                @Html.ValidationMessage("fechaApertura", new { @class = "text-danger" })
            </div>

            <div style="margin:auto">
                <input type="submit" value="Enviar" class="btn btn-primary"/>
                @Html.ActionLink("Regresar","Index","Sucursal",null, new { @class="btn btn-danger"})
            </div>
        }
    </div>
</div>

<script>
    var frmSucursal = document.getElementById("frmSucursal");
    frmSucursal.onsubmit = function (e) {
        e.preventDefault();
        if (confirm("¿Desea agregar los combios") == 1) {
            frmSucursal.submit();
        }
    }
</script>

MiPrimeraAplicacionWebConEntityFramework/Views/Sucursal/Editar.cshtml
@using MiPrimeraAplicacionWebConEntityFramework.Models
@model SucursalCLS
@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>

<div class="row">
    <div class="col-md-6">
        @using (Html.BeginForm("Editar", "Sucursal", FormMethod.Post, new { @id="frmSucursal"}))
        {
            <div>
                @Html.LabelFor(p => p.iidsucursal)
                @Html.TextBoxFor(p => p.iidsucursal, new { @class = "form-control", @readOnly = true })
                @Html.ValidationMessage("iidsucursal", new { @class = "text-danger" })
            </div>

            <div>
                @Html.LabelFor(p => p.nombre)
                @Html.TextBoxFor(p => p.nombre, new { @class = "form-control" })
                @Html.ValidationMessage("nombre", new { @class = "text-danger" })
            </div>

            <div>
                @Html.LabelFor(p => p.direccion)
                @Html.TextBoxFor(p => p.direccion, new { @class = "form-control" })
                @Html.ValidationMessage("direccion", new { @class = "text-danger" })
            </div>

            <div>
                @Html.LabelFor(p => p.telefono)
                @Html.TextBoxFor(p => p.telefono, new { @class = "form-control" })
                @Html.ValidationMessage("telefono", new { @class = "text-danger" })
            </div>

            <div>
                @Html.LabelFor(p => p.email)
                @Html.TextBoxFor(p => p.email, new { @class = "form-control" })
                @Html.ValidationMessage("email", new { @class = "text-danger" })
            </div>

            <div>
                @Html.LabelFor(p => p.fechaApertura)
                @Html.EditorFor(p => p.fechaApertura, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessage("fechaApertura", new { @class = "text-danger" })
            </div>

            <div style="margin:auto">
                <input type="submit" value="Enviar" class="btn btn-primary" />
                @Html.ActionLink("Regresar", "Index", "Sucursal", null, new {@class="btn btn-danger"})
            </div>
        }
    </div>
</div>

<script>
    var frmSucursal = document.getElementById("frmSucursal");
    frmSucursal.onsubmit = function (e) {
        e.preventDefault();
        if (confirm("¿Desea guardar los combios") == 1) {
            frmSucursal.submit();
        }
    }
</script>

MiPrimeraAplicacionWebConEntityFramework/Views/Sucursal/Index.cshtml
@using MiPrimeraAplicacionWebConEntityFramework.Models
@model List<SucursalCLS>
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@Html.ActionLink("Agregar", "Agregar", "Sucursal", null, new { @class = "btn btn-primary" })

@using (Html.BeginForm("Index", "Sucursal", FormMethod.Get, new { @id="frmBusqueda"}))
{

    @Html.Label("Ingrese nombre Sucursal")
    @Html.TextBox("nombre")

    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <td>@Html.LabelFor(p => Model[0].iidsucursal)</td>
                <td>@Html.LabelFor(p => Model[0].nombre)</td>
                <td>@Html.LabelFor(p => Model[0].telefono)</td>
                <td>@Html.LabelFor(p => Model[0].email)</td>
                <td>Operaciones</td>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.iidsucursal</td>
                    <td>@item.nombre</td>
                    <td>@item.telefono</td>
                    <td>@item.email</td>
                    <td>
                        @Html.ActionLink("Editar", "Editar", "Sucursal", new { id = @item.iidsucursal }, new { @class = "btn btn-primary" })
                        @Html.ActionLink("Eliminar", "Eliminar", "Sucursal", new { id = @item.iidsucursal }, new { @class = "btn btn-danger", @onclick = "eliminarSucursal()" })
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
    <script>
        function eliminarSucursal() {
            if (confirm("¿Desea eliminar el registro realmente?") == 1) {
                //Pone Si
                alert("Se elimino correctamente");
            } else {
                //Pone No
                event.preventDefault();
            }
        }

        var nombre = document.getElementById("nombre");
        nombre.onkeyup = function () {
            var frmBusqueda = document.getElementById("frmBusqueda");
            frmBusqueda.submit();
        }
    </script>